version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
      
    commands:
      - echo Entered the install phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - mvn clean
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - target/hello-world-cicd-0.0.1.jar